### ISSUE TITLE
Containers.start response handling

### ISSUE THREAD

**Issue by setiseta** [shoxxdj/harbor-master-wb#1]
Hello,

thanks for the lib.
i think i found something not working as expected.
if i use the client.containers().start(container.Id); I'm getting a error with status code 204.
As of the docker documentation this is the code for success.
204 no error
304 container already started/stopped

i think they should be added in
harbor-master/lib/endpoints/containers.js
Line: 233
Line: 253
And on line 273 only the code 204 cause ther is no code 304 on restart.

hopefully i'm not wrong.
should i open a PR?

Best regards

( arhea/harbor-master Issue #9 but the repo for harbor-master seems dead. )

**Comment by shoxxdj** [comment]
Hello ! 
Sorry for this little delay. 
If you already patched it you can do a PR, else I add it to my todolist :) 

Regards;

**Comment by shoxxdj** [comment]
Closing this issue after merge :)
